---
labels:
  # Kinds.
  - name: "kind/bug"
    color: "#D73A4A"
    description: "Something isn't working"
  - name: "kind/design"
    color: "#8000FF"
    description: "Visual aspect"
  - name: "kind/docs"
    color: "#000BE0"
    description: "Document the project"
  - name: "kind/enhancement"
    color: "#A2EEEF"
    description: "Improve an existing feature"
  - name: "kind/optimization"
    color: "#A2EEEF"
    description: "Optimize an existing feature"
  - name: "kind/feature"
    color: "#A2EEEF"
    description: "New feature request"
  - name: "kind/infrastructure"
    color: "#387499"
    description: "Issue regarding the local or cloud infrastructure setup"
  - name: "kind/automation"
    color: "#387499"
    description: "Automate your tasks"
  - name: "kind/security"
    color: "#993333"
    description: "CVEs and other security flaws"

  # Feedback.
  - name: "feedback/question"
    color: "#D876E3"
    description: "Further information is requested"
  - name: "feedback/discussion"
    color: "#D876E3"
    description: "Discuss a specific aspect of the project"

  # T-Shirt sizes.
  - name: "size/XS"
    color: "#00FF00"
    description: "Extra small (0-9 lines of changes)"
  - name: "size/S"
    color: "#CCFF66"
    description: "Small  (10-29 lines of changes)"
  - name: "size/M"
    color: "#FFFF00"
    description: "Medium  (30-99 lines of changes)"
  - name: "size/L"
    color: "#FF9933"
    description: "Large  (100-499 lines of changes)"
  - name: "size/XL"
    color: "#B60205"
    description: "Extra large  (500-999 lines of changes)"
  - name: "size/XXL"
    color: "#8B0000"
    description: "Extra Extra Large  (1000+ lines of changes)"

  # Experience.
  - name: "exp/beginner"
    color: "#CBE4CE"
    description: "Good for newcomers"
  - name: "exp/intermediate"
    color: "#CBE4CE"
    description: "Show off your skills"
  - name: "exp/expert"
    color: "#CBE4CE"
    description: "I have nothing else to teach you"

  # Statuses.
  - name: "status/claimed"
    color: "#FBCA04"
    description: "Assigned"
  - name: "status/help wanted"
    color: "#008672"
    description: "Could use an extra brain"
  - name: "status/more info needed"
    color: "#008672"
    description: "Needs clarification"
  - name: "status/invalid"
    color: "#D2DAE1"
    description: "No further triaging"
  - name: "status/wontfix"
    color: "#D2DAE1"
    description: "Fix is too controversial or do not want to implement it"
  - name: "status/duplicate"
    color: "#D2DAE1"
    description: "This issue or pull request already exists"
  - name: "status/review-carefully!"
    color: "#B60205"
    description: "Requires extra attention during review"

  # Environment.
  - name: "environment/dev"
    color: "#F7FBFF"
    description: "Developer environment"
  - name: "environment/prod"
    color: "#F7FBFF"
    description: "Production environment"

  # Bots.
  - name: "dependencies"
    color: "#0366d6"
    description: "Pull requests that update a dependency file"
  - name: "do-not-merge"
    color: "#DC143C"
    description: "Prevents PRs with this label to be merged"
